name = "global-peace-platform"
compatibility_date = "2024-03-22"

[vars]
PROJECT_ID = "ai-services-7abb5"
LOCATION = "us-central1"
MODEL_ID = "gemini-1.0-pro-001"
YOUTUBE_PLAYLIST_ID = "PLrD7_d5Wv_AASd184IOK8ObrA6M0DbmWH"

[pages]
main = "frontend"

[[d1_databases]]
binding = "DB"
database_name = "youthentrepreneurship"
database_id = "95c0e18c-d118-43f0-97ec-ec636f51ddca"

[[r2_buckets]]
binding = "R2"
bucket_name = "gpw-media"
